version: "3"

services:
  mongodb1:
    image: mongo:4.4
    restart: always
    container_name: mongodb1
    volumes:
      - mongodata1:/data/db
    ports:
      - 27017:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

  mongodb2:
    image: mongo:4.4
    restart: always
    container_name: mongodb2
    volumes:
      - mongodata2:/data/db
    ports:
      - 27018:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

  mongodb3:
    image: mongo:4.4
    restart: always
    container_name: mongodb3
    volumes:
      - mongodata3:/data/db
    ports:
      - 27019:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    container_name: "mongosetup"
    depends_on:
      - mongodb1
    volumes:
      - mongostatus:/data/

volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  mongostatus:
